### ISSUE TITLE
#37-Seleccionar idioma

### ISSUE THREAD

**Issue by aolle99** [Green-Wheel/MobileAPP#1]
Com a usuari autenticat al sistema vull poder seleccionar l'idioma en què es mostran els texts de l'aplicació.
Tasques:
- [x] #103 Interacció de seleccionar idioma
- [x] #104 Creació de sistema d'internacionalització
- [x] #138 Guardar selecció usuari/dispositiu per defecte
- [x] #139 Obtenir idioma de l'usuari
