### ISSUE TITLE
#51-Iniciar ruta

### ISSUE THREAD

**Issue by aolle99** [Green-Wheel/MobileAPP#12]
Com a usuari autenticat vull iniciar una ruta per tal de traçar un camí desitjat des de la meva ubicació a un altre punt.

- [x] #131 Calcular ruta (distància, temps, etc)
- [ ] #132 Dibuixar ruta sobre el mapa
- [ ] #157 Mostrar a Google maps
