### ISSUE TITLE
#39-Afegir carregador

### ISSUE THREAD

**Issue by arnau147** [Green-Wheel/MobileAPP#4]
Com a usuari autenticat al sistema vull afegir un nou carregador per tal de llogar-lo a la resta d’usuaris.

- [ ] #105 Recaptació informació punt de càrrega (formulari)
- [ ] #106 Guardar informació al sistema 
- [ ] #142 Interacció botó afegir publicació
- [ ] #143 Guardar imatges a storage
