### ISSUE TITLE
#80-Filtrar carregadors

### ISSUE THREAD

**Issue by aolle99** [Green-Wheel/MobileAPP#5]
Com a usuari conductor vull poder filtrar carregadors de manera que pugui trobar el carregador més bo per als meus recorreguts.

- [ ] #112 Afegir recomanacions de direccions al cercador
- [ ] #113 Obtenir els carregadors tenint en compte els filtres passats
- [ ] #114 Mostrar resultats en format llistat (depèn de veure els punts de propietari)
- [ ] #134 Fer cercador d'ubicacions
- [ ] #151 Creació dels filtres sobre el mapa
- [x] #156 Bottom bar amb botó de cotxes i bicicletes + icono xat
