### ISSUE TITLE
#35-Canviar de Perfil

### ISSUE THREAD

**Issue by Isslam1** [Green-Wheel/MobileAPP#6]
Tasques:

- [x]   #102 Pàgina principal llogater
- [x]   #128 Pàgina base perfil (pàgina en blanc)
- [x]   #137 Botó + navegació per a canviar d'un perfil a l'altre
