### ISSUE TITLE
#38-Veure carregador concret 

### ISSUE THREAD

**Issue by MikierXXV** [Green-Wheel/MobileAPP#8]
Com a usuari autenticat al sistema vull poder veure un carregador concret per tal de veure més informació sobre aquest

- [ ] #89 Interacció de selecció punt de carregador (fer click sobre icona)
- [ ] #90 Mostrar tarjeta amb informació bàsica (1/3 pantalla)
- [ ] #140 Obtenir informació del punt
- [ ] #141 Mostrar informació detallada (pantalla completa)
